# Generated by Django 6.0.6 on 2026-06-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poststream',
            name='slug',
            field=models.SlugField(default='blank', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poststream',
            name='posts',
            field=models.ManyToManyField(blank=True, to='blog.blogpost'),
        ),
    ]
