# Generated by Django 6.0.6 on 2026-06-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_options_blogpost_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['sort_order', '-updated_at']},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
