# Generated by Django 6.0.6 on 2026-06-30 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0008_blogpost_related_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(choices=[('wide', 'Wide'), ('narrow', 'Narrow')], max_length=10)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.poststream')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
